# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

# This continuous integration pipeline is triggered anytime a user pushes code to the repo.
# This pipeline builds the Wpf project, runs unit tests, then saves the MSIX build artifact.
name:  Wpf Continuous Integration

# Trigger on every master branch push and pull request
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build:

    strategy:
      matrix:
        targetplatform: [x86, x64]

    runs-on: windows-latest

    env:
      #App_Packages_Directory: AppPackages
      #SigningCertificate: GitHubActionsDemo.pfx
      Solution_Path: SophiApp\SophiApp.sln
      #Test_Project_Path: MyWpfApp.Tests\MyWpfApp.Tests.csproj
      Wpf_Project_Path: SophiApp\SophiApp.csproj
      #Wap_Project_Directory: MyWpfApp.Package
      #Wap_Project_Name: MyWpfApp.Package.wapproj

    steps:
    #- name: Checkout
    #  uses: actions/checkout@v2
    #  with:
    #   fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    # Use Nerdbank.GitVersioning to set version variables: https://github.com/AArnott/nbgv
    #- name: Use Nerdbank.GitVersioning to set version variables
    #  uses: aarnott/nbgv@v0.3
    #  with:
    #    setAllVars: true

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100

    # Add  MsBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.0

    # Update the version before build
    #- name: Update manifest version
    #  run: |
    #    [xml]$manifest = get-content ".\$env:Wap_Project_Directory\Package.appxmanifest"
    #    $manifest.Package.Identity.Version = "$env:NBGV_SimpleVersion.0"
    #    $manifest.save(".\$env:Wap_Project_Directory\Package.appxmanifest")

    # Test
    #- name: Execute Unit Tests
    #  run: dotnet test $env:Test_Project_Path

    # Restore the application
    - name:  Restore the Wpf application to populate the obj folder
      run: msbuild $env:Solution_Path /t:Restore /p:Configuration=$env:Configuration /p:RuntimeIdentifier=$env:RuntimeIdentifier
      env:
        Configuration: Release
        RuntimeIdentifier: win-${{ matrix.targetplatform }}

    # Decode the Base64 encoded Pfx
    #- name: Decode the Pfx
    #  run: |
    #    $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
    #   $currentDirectory = Get-Location
    #    $certificatePath = Join-Path -Path $currentDirectory -ChildPath $env:Wap_Project_Directory -AdditionalChildPath $env:SigningCertificate
    #    [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

    # Build the Windows Application Packaging project
    #- name: Build the Windows Application Packaging Project (wapproj)
    #  run: msbuild $env:Solution_Path /p:Platform=$env:TargetPlatform /p:Configuration=$env:Configuration /p:UapAppxPackageBuildMode=$env:BuildMode /p:AppxBundle=$env:AppxBundle /p:PackageCertificateKeyFile=$env:SigningCertificate /p:PackageCertificatePassword=${{ secrets.Pfx_Key }}
    #  env:
    #    AppxBundle: Never
    #    BuildMode: SideloadOnly
    #    Configuration: Debug
    #    TargetPlatform: ${{ matrix.targetplatform }}

    # Remove the .pfx
    #- name: Remove the .pfx
    #  run: Remove-Item -path $env:Wap_Project_Directory\$env:SigningCertificate

    # Upload the MSIX package: https://github.com/marketplace/actions/upload-artifact
    #- name: Upload build artifacts
    #  uses: actions/upload-artifact@v1
    #  with:
    #    name: MSIX Package
    #    path: ${{ env.Wap_Project_Directory }}\${{ env.App_Packages_Directory }}
